twig:
    default_path: '%kernel.project_dir%/templates'

twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        App\Twig\Component\: 'components/'

when@test:
    twig:
        strict_variables: true
